apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: init
  name: init
spec:
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', 'touch  /etc/qqq;']
  containers:
  - image: nginx
    name: init
    command: ['sh', '-c', 'if [ ! -f  "/etc/qqq"]; then  exit ; fi ;']
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
